export const LOAD_NAVIGATION_FOLDERS_DATA = "LOAD_NAVIGATION_FOLDERS_DATA";
export const LOAD_MAIL_LIST_DATA = 'LOAD_MAIL_LIST_DATA'; 
export const SET_ACTIVE_FOLDER = 'SET_ACTIVE_FOLDER';
export const LOAD_SELECTED_MAIL = 'LOAD_SELECTED_MAIL';